services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gj-backstage-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - gj-backstage

  postgres:
    image: postgres:15
    container_name: gj-backstage-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gj-backstage

  redis:
    image: redis:7-alpine
    container_name: gj-backstage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gj-backstage

volumes:
  postgres_data:
  redis_data:

networks:
  gj-backstage:
    driver: bridge
